# Generated by Django 2.2.4 on 2019-08-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
