# Generated by Django 2.2.4 on 2019-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190825_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='articles/'),
        ),
    ]
