# Generated by Django 2.2.4 on 2019-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='photos.tags'),
        ),
    ]
