# Generated by Django 2.2.4 on 2019-08-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190825_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='postor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.Postor'),
        ),
    ]
