# Generated by Django 2.2.4 on 2019-08-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='image',
            name='postor',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.DO_NOTHING, to='photos.Postor'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
