# Generated by Django 2.2.4 on 2019-08-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190825_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='postor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.Postor'),
        ),
    ]
