# Generated by Django 2.2.4 on 2019-08-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20190825_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
