# Generated by Django 2.2.4 on 2019-08-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_remove_image_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
