# Generated by Django 2.2.4 on 2019-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20190826_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='category',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='image',
            name='location_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
