# Generated by Django 2.2.4 on 2019-08-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
