# Generated by Django 2.2.4 on 2019-08-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20190827_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
