# Generated by Django 2.2.4 on 2019-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
